### ISSUE TITLE
Issue with the creation date

### ISSUE THREAD

**Issue by fbouteruche** [otosky/medium_stats#7]
Hi,

Here https://github.com/otosky/medium_stats/blob/dbe4164e07810213e0e3c211bf71b1662eedb4ec/medium_stats/scraper.py#L277, you assume that the activeAt is the creation date. Unfortunately, it doesn't. It is the time where you get your last follower.

As a consequence, when you get a new follower and you can set up a start date prior to this date anymore because of https://github.com/otosky/medium_stats/blob/dbe4164e07810213e0e3c211bf71b1662eedb4ec/medium_stats/scraper.py#L281

**Comment by otosky** [comment]
Woops, you're totally right - I just blindly assumed that was the creation time since I was testing on a dummy Publication with no followers 😳 .

It doesn't seem like the Publication creation time is included in the response json at all, so I'll likely just remove lines 277-283 entirely.  I'm not entirely sure why I kept in that functionality to reset the start_time in the first place...

**Comment by fbouteruche** [comment]
Hi Oliver,

First of all, thanks for this project. It really helped to get at speed quickly to grab my analytics data. 

I agree that you could remove lines 277-283. I've did it yesterday evening to apply a hot fix on my solution. It seems to work. If you want, I can contribute back to your code and make a PR.

Best regards,
François.

**Comment by fbouteruche** [comment]
I was thinking that you may end up with an issue with the --all option of the CLI. I assume you were using this trick for this.

**Comment by otosky** [comment]
@fbouteruche glad you're getting some use out of this!  please feel free to open a PR, I'd love to have another contributor!

You're correct that the `--all` CLI flag for publications will be affected.  I can see two avenues for addressing this:

1. set an arbitrary start-date way back in the past to ensure that all data is captured.
2. just disable the `--all` flag for publications and make start/end dates required params for the CLI.

As an end-user, would you find one option preferable?  Curious for your input, since I admittedly don't get alot of use out of this package at the moment.
